export const SET_FILTERVALUESLIST = "SET_FILTERVALUESLIST";
export const SET_FILTERVALUESLIST_CORPORATE_ACTION = "SET_FILTERVALUESLIST_CORPORATE_ACTION";
export const SET_SAVESEARCHLIST = "SET_SAVESEARCHLIST";
